# Generated by Django 5.1.5 on 2025-03-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grades',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
