# Generated by Django 5.1.5 on 2025-03-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_course_userprofile_grades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='predicted_grades',
            field=models.FloatField(default=0),
        ),
    ]
