# Generated by Django 5.1.5 on 2025-03-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_predicted_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=256)),
                ('questioning_dictionary', models.CharField(default='', max_length=10000)),
                ('verification_dictionary', models.CharField(default='', max_length=10000)),
                ('score', models.FloatField(default=0)),
            ],
        ),
    ]
