# Generated by Django 5.1.5 on 2025-03-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mockexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=256)),
                ('question', models.CharField(default='', max_length=10000)),
                ('answer', models.CharField(default='', max_length=10000)),
                ('suggestion', models.CharField(default='', max_length=10000)),
                ('weak_points', models.CharField(default='', max_length=1000)),
                ('correct', models.BooleanField(default='False')),
            ],
        ),
        migrations.DeleteModel(
            name='MockExam',
        ),
    ]
