# Generated by Django 5.1.5 on 2025-03-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userhistory_delete_mockexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_questions',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
